services:
  postgres:
    image: postgres:17.5
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
      POSTGRES_DB: petclinic
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    # override default postgres startup to enable full query + parameter logging
    command:
      - postgres
      - -c
      - log_statement=all               # log every SQL statement :contentReference[oaicite:0]{index=0}
      - -c
      - log_destination=stderr         # send logs to stderr so `docker logs` captures them (default destination) :contentReference[oaicite:1]{index=1}
      - -c
      - log_min_duration_statement=0   # also records duration for each statement


volumes:
  postgres_data: